name: build

on: [push, pull_request]

jobs:
  sh-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run sh-checker
        uses: luizm/action-sh-checker@v0.3.0
        env:
          SHFMT_OPTS: -i 4 -d
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 24.5
          - 25.1
          - 25.2
          - 25.3
          - 26.1
          - 26.2
          - 26.3
          - 27.1
          - 27.2
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Emacs
        uses: purcell/setup-emacs@v3.0
        with:
          version: ${{ matrix.emacs_version }}
      - name: Lint Elisp
        uses: leotaku/elisp-check@v1.2 # Newer versions break on older Emacs (eg: 24)
        with:
          check: melpa
          file: "*.el"
          ignore_warnings: false
          warnings_as_errors: true
